# Permalinks
permalink:           pretty

# Setup
title:               Z.W. Miller
tagline:             A Moderately Okay Data Science Blog
url:                 http://reemalmuqbil.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Reem Almoqbil
  url:               
  email:             reem.almuqbil@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/reemalmuqbil

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
